import type { Referral } from '@/lib/types'

export const specialistReferralMockData: Referral[] = [
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Accepted',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 1,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Rejected',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 2,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Accepted',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 3,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Accepted',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 4,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Rejected',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 5,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Rejected',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 6,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Accepted',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 7,
  },
  {
    referralId: 87327462,
    patientName: 'Peter Pan',
    status: 'Accepted',
    referringProvider: 'Dr Strange',
    receivingProvider: 'Dr Ojiaku',
    dateReferred: '06/01/25',
    index: 8,
  },
]
